name: 'AWS Deploy S3'
description: 'Deploy static files to AWS S3'
branding:
  icon: upload-cloud
  color: green
inputs:
  region:
    description: 'AWS Region of S3 Bucket'
    required: true
    default: 'us-east-1'
  bucket:
    description: 'Name of S3 Bucket'
    required: true
  source:
    description: 'A Local Source Directory to Upload'
    required: true
    default: './dist'
  target:
    description: 'A Remote Target Directory to Upload'
    required: true
    default: ''
  tags:
    description: 'The tag-set for the object. The tag-set must be encoded as URL Query parameters. (For example, "Key1=Value1")'
    required: false
    default: ''
  clear-target:
    description: 'Indicates whether the destination directory should be cleared'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
